# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-10 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0004_uploadedimage_title_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Uploaded image'),
        ),
    ]
