# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-11 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0005_auto_20181010_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='bs_images',
        ),
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='title',
            new_name='bs_thename',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='description',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='bs_theimg',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='bs_title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='bs_writer',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of the uploaded image'),
        ),
    ]
