# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-11 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0008_auto_20181011_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Uploaded image')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='bs_images',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='bs_thename',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='location name'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='bs_title',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='Title of intro image'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='bs_writer',
            field=models.CharField(default='Unknown Picture', max_length=255, verbose_name='writer of intro image'),
        ),
        migrations.AddField(
            model_name='subimage',
            name='uploadedimage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='imageupload.UploadedImage'),
        ),
    ]
