# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0009_auto_20181012_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subimage',
            name='uploadedimage',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='bs_images',
            field=models.ManyToManyField(to='imageupload.SubImage'),
        ),
    ]
