# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-11 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0010_auto_20181012_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='bs_images',
        ),
        migrations.AddField(
            model_name='subimage',
            name='uploadedimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imageupload.UploadedImage'),
        ),
    ]
