# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-12 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0011_auto_20181012_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subimage',
            name='uploadedimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='imageupload.UploadedImage'),
        ),
    ]
